name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    types: [opened, synchronize, enqueued]
    branches:
      - '**'  # All branches

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Trying to merge ${{ github.ref }} into ${{ github.base_ref }}..."
      - name: Check out repository code - force fetch
        uses: actions/checkout@v4
        with:
          # Fetches all branches and tags and sets up a detached HEAD.
          fetch-depth: 0
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Prints out the pull_request information
        run: |
          echo "Pull Request Number: ${{ github.event.number }}"
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Pull Request Body: ${{ github.event.pull_request.body }}"
          echo "Pull Request Author: ${{ github.event.pull_request.user.login }}"
          echo "Pull Request Assignee: ${{ github.event.pull_request.assignee.login }}"
          echo "Pull Request Reviewers: ${{ github.event.pull_request.requested_reviewers }}"
          echo "Pull Request Labels: ${{ github.event.pull_request.labels }}"
          echo "Pull Request Milestone: ${{ github.event.pull_request.milestone }}"
          echo "Pull Request Created At: ${{ github.event.pull_request.created_at }}"
          echo "Pull Request Updated At: ${{ github.event.pull_request.updated_at }}"
          echo "Pull Request Closed At: ${{ github.event.pull_request.closed_at }}"
          echo "Pull Request Merged At: ${{ github.event.pull_request.merged_at }}"
          echo "Pull Request Draft: ${{ github.event.pull_request.draft }}"
          echo "Pull Request Merged: ${{ github.event.pull_request.merged }}"
          echo "Pull Request Mergeable: ${{ github.event.pull_request.mergeable }}"
          echo "Pull Request Merged By: ${{ github.event.pull_request.merged_by.login }}"
          echo "Pull Request Base: ${{ github.event.pull_request.base.ref }}"
          echo "Pull Request Head: ${{ github.event.pull_request.head.ref }}"
          echo "Pull Request Commits: ${{ github.event.pull_request.commits }}"
          echo "Pull Request Changed Files: ${{ github.event.pull_request.changed_files }}"
          echo "Pull Request Additions: ${{ github.event.pull_request.additions }}"
          echo "Pull Request Deletions: ${{ github.event.pull_request.deletions }}"
          echo "Pull Request Review Comments: ${{ github.event.pull_request.review_comments }}"
          echo "Pull Request Review Comments URL: ${{ github.event.pull_request.review_comments_url }}"
          echo "Pull Request Comments: ${{ github.event.pull_request.comments }}"
          echo "Pull Request Comments URL: ${{ github.event.pull_request.comments_url }}"
          echo "Pull Request Statuses URL: ${{ github.event.pull_request.statuses_url }}"
          echo "Pull Request Commits URL: ${{ github.event.pull_request.commits_url }}"
          echo "Pull Request Review Comment URL: ${{ github.event.pull_request.review_comment_url }}"
          echo "Pull Request Comments URL: ${{ github.event.pull_request.comments_url }}"
          echo "Pull Request Issue URL: ${{ github.event.pull_request.issue_url }}"
          echo "Pull Request URL: ${{ github.event.pull_request.url }}"
          echo "Pull Request HTML URL: ${{ github.event.pull_request.html_url }}"
          echo "Pull Request Diff URL: ${{ github.event.pull_request.diff_url }}"
          echo "Pull Request Patch URL: ${{ github.event.pull_request.patch_url }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Pull Request Node ID: ${{ github.event.pull_request.node_id }}"
          echo "Pull Request ID: ${{ github.event.pull_request.id }}"
          echo "Pull Request User ID: ${{ github.event.pull_request.user.id }}"
          echo "Pull Request User Node ID: ${{ github.event.pull_request.user.node_id }}"
          echo "Pull Request User Avatar URL: ${{ github.event.pull_request.user.avatar_url }}"
          echo "Pull Request User Gravatar ID: ${{ github.event.pull_request.user.gravatar_id }}"

      - name: List out changed files
        run: | # Runs the scripts/list_changed_files.py
          pwd
          python3 scripts/list_changed_files.py "${{ github.base_ref }}"
